edge_functions:
  -
    path: "src/messages.js"
    domain: "preview.muriloazion123.com.br"
    env: "preview"
    origin: "httpbin.org"
    name: "Nome no RTM"
    args:
      arg1: valor1
      arg2: valor2
    path_uri: "/api/messages/"
    active: true
  -
    path: "src/content.js"
    domain: "www.muriloazion123.com.br"
    env: "production"
    origin: "httpbin.org"
    name: "Production function that show some content"
    args:
      nome: azeight
      score: 10
    path_uri: "/api/content/"
    active: true
  -
    path: "src/hackton2022.js"
    domain: "preview.muriloazion123.com.br"
    env: "preview"
    origin: "httpbin.org"
    name: "HACKATON function that show some content"
    args:
      nome: azeight
      score: 10
    path_uri: "/api/hackaton2022/"
    active: true
